//
//  Typesetter.swift
//  CodeEditTextView
//
//  Created by Khan Winter on 6/21/23.
//

import AppKit
import CoreText

/// The `Typesetter` is responsible for producing text fragments from a document range. It transforms a text line
/// and attachments into a sequence of `LineFragment`s, which reflect the visual structure of the text line.
///
/// This class has one primary method: ``typeset(_:documentRange:displayData:markedRanges:attachments:)``, which
/// performs the typesetting algorithm and breaks content into runs using attachments.
///
/// To retrieve the line fragments generated by this class, access the ``lineFragments`` property.
final public class Typesetter {
    struct ContentRun {
        let range: NSRange
        let type: RunType

        enum RunType {
            case attachment(AnyTextAttachment)
            case string(CTTypesetter)
        }
    }

    public var documentRange: NSRange?
    public var lineFragments = TextLineStorage<LineFragment>()

    // MARK: - Init & Prepare

    public init() { }

    public func typeset(
        _ string: NSAttributedString,
        documentRange: NSRange,
        displayData: TextLine.DisplayData,
        markedRanges: MarkedRanges?,
        attachments: [AnyTextAttachment] = []
    ) {
        let string = makeString(string: string, markedRanges: markedRanges)
        lineFragments.removeAll()

        // Fast path
        if string.length == 0 {
            typesetEmptyLine(displayData: displayData, string: string)
            return
        }

        // A degenerate wrap width (zero, negative, NaN) must not typeset non-empty content as empty
        // fragments or stall layout; treat it as unwrapped instead.
        let displayData = displayData.maxWidth > 0 ? displayData : TextLine.DisplayData(
            maxWidth: .greatestFiniteMagnitude,
            lineHeightMultiplier: displayData.lineHeightMultiplier,
            estimatedLineHeight: displayData.estimatedLineHeight,
            breakStrategy: displayData.breakStrategy
        )

        // Cache lookup. We skip caching whenever the result depends on per-instance state we
        // don't fold into the key (attachments and marked ranges). That's the rare path; the
        // hot path is unchanged unedited lines, which always hit cache.
        let cacheable = attachments.isEmpty && markedRanges == nil
        let cacheKey: TypesetCacheKey? = cacheable ? .make(string: string, displayData: displayData) : nil

        if let key = cacheKey, let cached = TypesetCache.shared.get(key) {
            let lines = buildItems(from: cached.fragments, lineHeightMultiplier: displayData.lineHeightMultiplier)
            lineFragments.build(from: lines, estimatedLineHeight: cached.maxHeight)
            return
        }

        let (lines, maxHeight) = typesetLineFragments(
            string: string,
            documentRange: documentRange,
            displayData: displayData,
            attachments: attachments
        )

        if let key = cacheKey {
            // Snapshot the typeset output for future hits. We store metrics + CTLines (immutable)
            // and reconstruct LineFragment instances per hit since `documentRange` is mutated by
            // the layout manager downstream.
            var fragmentsSnapshot: [CachedFragment] = []
            fragmentsSnapshot.reserveCapacity(lines.count)
            for item in lines {
                guard let single = item.data.contents.first,
                      case let .text(ctLine) = single.data else {
                    // Mixed content (attachments) - shouldn't reach here because cacheable=false,
                    // but bail defensively rather than caching a partial result.
                    fragmentsSnapshot.removeAll()
                    break
                }
                fragmentsSnapshot.append(
                    CachedFragment(
                        ctLine: ctLine,
                        length: item.length,
                        width: item.data.width,
                        height: item.data.height,
                        descent: item.data.descent
                    )
                )
            }
            if !fragmentsSnapshot.isEmpty {
                TypesetCache.shared.set(key, CachedTypesetResult(fragments: fragmentsSnapshot, maxHeight: maxHeight))
            }
        }

        lineFragments.build(from: lines, estimatedLineHeight: maxHeight)
    }

    /// Rebuild `BuildItem`s (with fresh `LineFragment` instances) from a cached typeset result.
    private func buildItems(
        from cached: [CachedFragment],
        lineHeightMultiplier: CGFloat
    ) -> [TextLineStorage<LineFragment>.BuildItem] {
        var out: [TextLineStorage<LineFragment>.BuildItem] = []
        out.reserveCapacity(cached.count)
        for c in cached {
            let fragment = LineFragment(
                contents: [.init(data: .text(line: c.ctLine), width: c.width)],
                width: c.width,
                height: c.height,
                descent: c.descent,
                lineHeightMultiplier: lineHeightMultiplier
            )
            out.append(.init(data: fragment, length: c.length, height: fragment.scaledHeight))
        }
        return out
    }

    private func makeString(string: NSAttributedString, markedRanges: MarkedRanges?) -> NSAttributedString {
        if let markedRanges {
            let mutableString = NSMutableAttributedString(attributedString: string)
            for markedRange in markedRanges.ranges {
                mutableString.addAttributes(markedRanges.attributes, range: markedRange)
            }
            return mutableString
        }

        return string
    }

    // MARK: - Create Content Lines

    /// Breaks up the string into a series of 'runs' making up the visual content of this text line.
    /// - Parameters:
    ///   - string: The string reference to use.
    ///   - documentRange: The range in the string reference.
    ///   - attachments: Any text attachments overlapping the string reference.
    /// - Returns: A series of content runs making up this line.
    func createContentRuns(
        string: NSAttributedString,
        documentRange: NSRange,
        attachments: [AnyTextAttachment]
    ) -> [ContentRun] {
        var attachments = attachments
        var currentPosition = 0
        let maxPosition = documentRange.length
        var runs: [ContentRun] = []

        while currentPosition < maxPosition {
            guard let nextAttachment = attachments.first else {
                // No attachments, use the remaining length
                if maxPosition > currentPosition {
                    let range = NSRange(location: currentPosition, length: maxPosition - currentPosition)
                    let substring = string.attributedSubstring(from: range)
                    runs.append(
                        ContentRun(
                            range: range,
                            type: .string(CTTypesetterCreateWithAttributedString(substring))
                        )
                    )
                }
                break
            }
            attachments.removeFirst()
            // adjust the range to be relative to the line
            let attachmentRange = NSRange(
                location: nextAttachment.range.location - documentRange.location,
                length: nextAttachment.range.length
            )

            // Use the space before the attachment
            if nextAttachment.range.location > currentPosition {
                let range = NSRange(start: currentPosition, end: attachmentRange.location)
                let substring = string.attributedSubstring(from: range)
                runs.append(
                    ContentRun(range: range, type: .string(CTTypesetterCreateWithAttributedString(substring)))
                )
            }

            runs.append(ContentRun(range: attachmentRange, type: .attachment(nextAttachment)))
            currentPosition = attachmentRange.max
        }

        return runs
    }

    // MARK: - Typeset Content Runs

    func typesetLineFragments(
        string: NSAttributedString,
        documentRange: NSRange,
        displayData: TextLine.DisplayData,
        attachments: [AnyTextAttachment]
    ) -> (lines: [TextLineStorage<LineFragment>.BuildItem], maxHeight: CGFloat) {
        let contentRuns = createContentRuns(string: string, documentRange: documentRange, attachments: attachments)
        var context = TypesetContext(documentRange: documentRange, displayData: displayData)

        for run in contentRuns {
            switch run.type {
            case .attachment(let attachment):
                context.appendAttachment(attachment)
            case .string(let typesetter):
                layoutTextUntilLineBreak(
                    context: &context,
                    string: string,
                    range: run.range,
                    typesetter: typesetter,
                    displayData: displayData
                )
            }
        }

        if !context.fragmentContext.contents.isEmpty {
            context.popCurrentData()
        }

        return (context.lines, context.maxHeight)
    }

    // MARK: - Layout Text Fragments

    func layoutTextUntilLineBreak(
        context: inout TypesetContext,
        string: NSAttributedString,
        range: NSRange,
        typesetter: CTTypesetter,
        displayData: TextLine.DisplayData
    ) {
        let substring = string.attributedSubstring(from: range)

        // Layout as many fragments as possible in this content run
        while context.currentPosition < range.max {
            // Offsets relative to `range`: where the next fragment's text starts, and the suggested end of the
            // break. Both are relative to the range being typeset, not the line.
            let relativeStart = context.currentPosition - range.location
            var lineBreak = typesetter.suggestLineBreak(
                using: substring,
                strategy: displayData.breakStrategy,
                subrange: NSRange(start: relativeStart, end: range.length),
                constrainingWidth: displayData.maxWidth - context.fragmentContext.width
            )

            if lineBreak <= relativeStart {
                // Forward progress invariant: always consume at least one composed character sequence.
                let sequence = (substring.string as NSString).rangeOfComposedCharacterSequence(at: relativeStart)
                lineBreak = min(sequence.max, range.length)
            }

            // The subrange of `range` making up the next fragment's text. This may not be the entire line
            let typesetSubrange = NSRange(start: relativeStart, end: lineBreak)
            let typesetData = typesetLine(typesetter: typesetter, range: typesetSubrange)

            // The typesetter won't tell us if 0 characters can fit in the constrained space. If the suggested
            // text overflows a fragment that already has content, break here and retry it on a fresh fragment.
            // Overflowing text on an empty fragment is kept as-is so layout always advances.
            if context.fragmentContext.width + typesetData.width > displayData.maxWidth
                && !context.fragmentContext.contents.isEmpty {
                context.popCurrentData()
                continue
            }

            // Amend the current line data to include this line, popping the current line afterwards
            context.appendText(typesettingRange: range, lineBreak: lineBreak, typesetData: typesetData)

            // If this isn't the end of the line, we should break so we pop the context and start a new fragment.
            if context.currentPosition != range.max {
                context.popCurrentData()
            }
        }
    }

    // MARK: - Typeset CTLines

    /// Typeset a new fragment.
    /// - Parameters:
    ///   - range: The range of the fragment.
    ///   - lineHeightMultiplier: The multiplier to apply to the line's height.
    /// - Returns: A new line fragment.
    private func typesetLine(typesetter: CTTypesetter, range: NSRange) -> CTLineTypesetData {
        let ctLine = CTTypesetterCreateLine(typesetter, CFRangeMake(range.location, range.length))
        var ascent: CGFloat = 0
        var descent: CGFloat = 0
        var leading: CGFloat = 0
        let width = CGFloat(CTLineGetTypographicBounds(ctLine, &ascent, &descent, &leading))
        let height = ascent + descent + leading
        return CTLineTypesetData(
            ctLine: ctLine,
            descent: descent,
            width: width,
            height: height
        )
    }

    /// Typesets a single, 0-length line fragment.
    /// - Parameter displayData: Relevant information for layout estimation.
    private func typesetEmptyLine(displayData: TextLine.DisplayData, string: NSAttributedString) {
        let typesetter = CTTypesetterCreateWithAttributedString(string)
        // Insert an empty fragment
        let ctLine = CTTypesetterCreateLine(typesetter, CFRangeMake(0, 0))
        let fragment = LineFragment(
            contents: [.init(data: .text(line: ctLine), width: 0.0)],
            width: 0,
            height: displayData.estimatedLineHeight / displayData.lineHeightMultiplier,
            descent: 0,
            lineHeightMultiplier: displayData.lineHeightMultiplier
        )
        lineFragments.build(
            from: [.init(data: fragment, length: 0, height: fragment.scaledHeight)],
            estimatedLineHeight: 0
        )
    }

    deinit {
        lineFragments.removeAll()
    }
}
